apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
      matchLabels:
        app: product-service
  replicas: 3
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: pelusa0303/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080