services:
  # ZooKeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
      
  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Service Discovery (Eureka)
  eureka:
    container_name: eureka-server
    build:
      context: ../discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"  # Expose the Eureka dashboard on port 8761
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"  # Disable client registration
      EUREKA_CLIENT_FETCH_REGISTRY: "false"  # Disable registry fetching
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]  # Check if Eureka is healthy
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - inventory-service-network  # Connect to a custom network

  # MongoDB for Inventory Microservice
  mongo:
    container_name: mongo-db
    image: mongo:latest  # Use the latest MongoDB image
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-volume:/data/db
    ports:
      - "27017:27017"  # Expose MongoDB port
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:admin@mongo:27017/?authSource=admin --quiet
      interval: 10s  
      timeout: 10s   
      retries: 5      
    networks:
      - inventory-service-network  # Connect to a custom network

  # PostgreSQL Database
  postgresql:
    container_name: postgresql-db
    image: postgres:latest  # Use the latest PostgreSQL image
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: postgres  # Name of the database
      POSTGRES_USER: postgres  # PostgreSQL user
      POSTGRES_PASSWORD: root  # PostgreSQL user password
    volumes:
      - postgres-volume:/data/db
    networks:
      - microservices-network  # Connect to a custom network

  # Product Microservice
  product:
    container_name: product-service
    build:
      context: ./product-service  # Path to the product microservice directory
      dockerfile: Dockerfile  # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "8090:8090"  # Expose product service on port 8090
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_PROFILES_ACTIVE: prod  # Specify the active profile
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - eureka  # Wait for Eureka to be up
      - postgresql  # Wait for PostgreSQL to be up
    networks:
      - microservices-network  # Connect to a custom network

  # Product Microservice
  order:
    container_name: order-service
    build:
      context: ./order-service  # Path to the order microservice directory
      dockerfile: Dockerfile  # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "8090:8090"  # Expose order service on port 8090
    environment:
      SPRING_APPLICATION_NAME: order-service
      SPRING_PROFILES_ACTIVE: prod  # Specify the active profile
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - eureka  # Wait for Eureka to be up
      - postgresql  # Wait for PostgreSQL to be up
    networks:
      - microservices-network  # Connect to a custom network

# Inventory Microservice
  inventory:
    container_name: inventory-service
    build:
      context: .  # Path to the inventory microservice directory
      dockerfile: Dockerfile  # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "8091:8091"  # Expose inventory service on port 8091
    environment:
      SPRING_APPLICATION_NAME: inventory-service
      SPRING_PROFILES_ACTIVE: prod  
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongo:27017/inventory-service?authSource=admin
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
    depends_on:
      eureka:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka:8761"] 
      interval: 15s
      timeout: 1s 
      retries: 2
    networks:
      - microservices-network  # Connect to a custom network

  # API Gateway (Spring Cloud Gateway or Zuul)
  api-gateway:
    container_name: api-gateway
    build:
      context: ./gateway  # Path to the API Gateway directory
      dockerfile: Dockerfile  # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "6001:6001"  # Expose API Gateway on port 6001
    environment:
      SPRING_APPLICATION_NAME: gateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/  # Change localhost to eureka
    depends_on:
      eureka:
       condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka:8761"] 
      interval: 15s
      timeout: 1s 
      retries: 2
    networks:
      - microservices-network  # Connect to a custom network

networks:
  microservices-network:  # Define a custom network for service communication
    driver: bridge

volumes:
  mongo-volume: 
  postgres-volume: