apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
      matchLabels:
        app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: pelusa0303/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8092