apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cm9vdA==     
  DB_NAME: cG9zdGdyZXM=         
  DB_SERVER: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
