services:
  # ZooKeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - product-service-network  # Connect to a custom network
      
  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - product-service-network  # Connect to a custom network

  # PostgreSQL Database
  postgresql:
    container_name: postgresql-db
    image: postgres:latest  # Use the latest PostgreSQL image
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    environment:
      POSTGRES_DB: postgres  # Name of the database
      POSTGRES_USER: postgres  # PostgreSQL user
      POSTGRES_PASSWORD: root  # PostgreSQL user password
    volumes:
      - postgres-volume:/data/db
    networks:
      - product-service-network  # Connect to a custom network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Product Microservice
  product:
    container_name: product-service
    build:
      context: ../product-service  # Path to the product microservice directory
      dockerfile: Dockerfile  # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "8090:8090"  # Expose product service on port 8090
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_PROFILES_ACTIVE: prod 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - postgres-volume:/data/db
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - product-service-network  # Connect to a custom network

networks:
  product-service-network: 

volumes:
  postgres-volume: