pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Set Up') {
            steps {
                sh "docker stop sonarqube || true"
                sh "docker start sonarqube || true"
                sh "docker stop product-service || true"
                sh "docker rm product-service || true"
                sh "sleep 10"
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir("product-service") {
                    withSonarQubeEnv('SonarServer') {
                    sh "mvn clean package sonar:sonar \
                    -Dsonar.projectKey=product-service \
                    -Dsonar.projectName=product-service \
                    -Dsonar.sources=src/main"
                   }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('product-service') {
                    sh "docker build -t product-service ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('product-service') {
                   sh "docker run -d --name product-service -p 8091:8091 product-service"
                }
            }
        }
    }

    post {
        always {
            sh "docker stop sonarqube || true"
            sh "docker stop product-service || true"
            sh "docker rm product-service || true"
        }
    }
}
