pipeline {
    agent any

    parameters {
        booleanParam(name: 'skip_sonar', defaultValue: false, description: 'Set to true to run sonar analysis')
        booleanParam(name: 'build_container', defaultValue: false, description: 'Set to true to build the container')
        booleanParam(name: 'run_container', defaultValue: false, description: 'Set to true to run the container')
        booleanParam(name: 'deploy_container', defaultValue: false, description: 'Set to true to deploy the container')
    }

    tools {
        maven 'maven'
    }

    stages {
        stage('Set Up') {
            steps {
                sh "docker stop sonarqube || true"
                sh "docker start sonarqube || true"
                sh "docker stop product-service || true"
                sh "docker rm product-service || true"
            }
        }

        stage('SonarQube Analysis') {
            when { expression { params.skip_sonar } }
            steps {
                withSonarQubeEnv('SonarServer') {
                    sh "mvn clean package sonar:sonar \
                    -Dsonar.projectKey=product-service \
                    -Dsonar.projectName=product-service \
                    -Dsonar.sources=src/main"
                }
            }
        }

        stage('Build Docker Image') {
            when { expression { params.build_container } }
            steps {
                sh "docker build -t product-service ."
            }
        }

        stage('Run Docker Container') {
            when { expression { params.run_container } }
            steps {
                sh "docker run -d --name product-service -p 8090:8090 product-service"
            }
        }

        stage('Deploy Docker Container') {
            when { expression { params.deploy_container } }
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker_login', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                    sh 'docker tag product-service:latest pelusa0303/product-service:latest'
                    sh 'docker push pelusa0303/product-service:latest'
                }
            }
        }
    }
}
