apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
      matchLabels:
        app: inventory-service
  replicas: 3
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: pelusa0303/inventory-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
           - name: SPRING_PROFILES_ACTIVE
             value: prod
           - name: MONGO_USER
             valueFrom:
               secretKeyRef:
                 name: inventory-service-secrets
                 key: MONGO_USER
           - name: MONGO_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: inventory-service-secrets
                 key: MONGO_PASSWORD
           - name: MONGO_HOST
             valueFrom:
               secretKeyRef:
                 name: inventory-service-secrets
                 key: MONGO_HOST
           - name: MONGO_PORT
             valueFrom:
               secretKeyRef:
                name: inventory-service-secrets
                key: MONGO_PORT
           - name: MONGO_DB
             valueFrom:
               secretKeyRef:
                 name: inventory-service-secrets
                 key: MONGO_DB
           - name: KAFKA_SERVER
             valueFrom:
               configMapKeyRef:
                 name: inventory-service-config
                 key: KAFKA_SERVER
           - name: SERVER_PORT
             valueFrom:
                configMapKeyRef:
                 name: inventory-service-config
                 key: SERVER_PORT
