apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
      matchLabels:
        app: inventory-service
  replicas: 3
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8091