spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver  
  config:
    activate:
      on-profile: "prod"
  jpa: 
    show-sql: true
    properties:
      hibernate: 
        show_sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
