spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver  
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect 
    show-sql: false
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
