apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  selector:
      matchLabels:
        app: document-service
  replicas: 3
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: document-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8093