apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secrets
type: Opaque
data:
  aws:
    access:
      key: ${AWS_ACCESS_KEY:}
    secret:
      key: ${AWS_SECRET_KEY:}
    s3:
      bucket: ${AWS_S3_BUCKET:spring-medium-bucket}  