spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/microservices?authSource=admin
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
