services:
  # document Microservice
  document:
    container_name: document-service
    build:
      context: ../document-service  # Path to the document microservice directory
      dockerfile: Dockerfile  # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "8093:8093"  # Expose document service on port 8093
    environment:
      SPRING_APPLICATION_NAME: document-service
      SPRING_PROFILES_ACTIVE: prod 
    depends_on:
      eureka:
        condition: service_healthy
    restart: always
    networks:
      - document-service-network  # Connect to a custom network

networks:
  document-service-network: 