pipeline {
    agent any

    parameters {
        booleanParam(name: 'skip_sonar', defaultValue: false, description: 'Set to true to run sonar analysis')
        booleanParam(name: 'build_container', defaultValue: false, description: 'Set to true to build the container')
        booleanParam(name: 'run_container', defaultValue: false, description: 'Set to true to run the container')
        booleanParam(name: 'deploy_container', defaultValue: false, description: 'Set to true to deploy the container')
    }

    tools {
        maven 'maven'
    }

    stages {
        stage('Set Up') {
            steps {
                sh "docker stop sonarqube || true"
                sh "docker start sonarqube || true"
                sh "docker stop document-service || true"
                sh "docker rm document-service || true"
                sh "sleep 10"
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir("document-service") {
                    if (!params.skip_sonar) {
                      withSonarQubeEnv('SonarServer') {
                      sh "mvn clean package sonar:sonar \
                      -Dsonar.projectKey=document-service \
                      -Dsonar.projectName=document-service \
                      -Dsonar.sources=src/main"
                      }
                   }
                }
            }
        }

        stage('Build Docker Image') {
            when { expression { params.build_container != false } } 
            steps {
                dir('document-service') {
                    sh "docker build -t document-service ."
                }
            }
        }

        stage('Run Docker Container') {
            when { expression { params.run_container != false } } 
            steps {
                dir('document-service') {
                   sh "docker run -d --name document-service -p 8093:8093 document-service"
                }
            }
        }

        stage('Deploy Docker Container') {
            when { expression { params.run_container != false } } 
            steps {
                dir('document-service') {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker_login', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                      sh 'docker login -u $USERNAME -p $PASSWORD'
                      sh 'docker tag document-service:latest pelusa0303/document-service:latest'
                      sh 'docker push pelusa0303/document-service:latest'
                   }
                }
            }
        }
    }
}
